#!/usr/bin/env bash

clear

case $1 in
    migrate)
        php artisan migrate:fresh
        php artisan db:seed
        ;;
    jobs)
	      php artisan queue:work
	      ;;
    tests)
          ./vendor/bin/phpunit --testdox
          ;;
    up)
        docker-compose up -d
        echo ""
        echo "Application:  http://localhost/"
        echo "phpMyAdmin:   http://localhost:8080/"
        echo "MySQL server: localhost:3306"
        echo ""
        ;;
    down)
        docker-compose down
        ;;
esac

