version: '3'
services:

########################### Laravel App ###########################
  app:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    image: hakase-labs/laravel
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      mynet:
        ipv4_address: 10.5.0.10

  ########################### WebServer ###########################
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - './build/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      mynet:
        ipv4_address: 10.5.0.11

  ########################### MySQL Server ###########################
  db:
    image: mysql:latest
    container_name: MySQL
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: Main
      MYSQL_USER: user
      MYSQL_PASSWORD: fcuk
      MYSQL_ROOT_PASSWORD: fcuk
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      mynet:
        ipv4_address: 10.5.0.12

  ########################### phpmyadmin ###########################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
     - 8080:80
    environment:
      PMA_HOST: 10.5.0.12
      PMA_USER: user
      PMA_PASSWORD: fcuk
      PMA_ARBITRARY: 1
    networks:
      mynet:
        ipv4_address: 10.5.0.13

########################### Networks ###########################
networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
########################### Volumes ###########################
volumes:
  mysqldata:
    driver: local
